version: "3.7"

services:
  nginx:
    image: nginx:latest
    hostname: ng1
    ports:
      - "800:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    # depends_on:
    #   - php
    networks:
      - app-network

  nodeapp:
    build: .
    hostname: nodeapp1
    ports:
      - "8080:8080"
      # volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
      
# need to create a network for the nginx and nodeapp to communicate
networks:
  app-network:
    driver: bridge